<form method="POST" action = './index.php'>
    
    <fieldset>
        <label>login</label>
        <input type="email" name = 'user'>
          </fieldset>
          
             <fieldset>
        <label>password</label>
        <input type ="password" name='pass'>
           </fieldset>
           
            <fieldset>
        <label>formName</label>
        <input type="hidden">
          </fieldset>
          <button type="submit">dc</button>
          
</form>