<form method="POST" action="index.php">
    <fieldset>
        <label>firstName</label>
        <input type="texte" name ="firstName">
          </fieldset>
          
          <fieldset>
        <label>lastName</label>
        <input type="texte" name ="lastName">
          </fieldset>
          
          <fieldset>
        <label>email</label>
        <input type="email"name ="email">
          </fieldset>
          
          <fieldset>
        <label>password</label>
        <input type="password" name ="pass1">
          </fieldset>
          
          <fieldset>
        <label>confirmPassword</label>
        <input type="password"name ="pass2">
          </fieldset>
          
          <fieldset>
        <label>formName</label>
        <input type="hidden">
          </fieldset>
          
            <button type="submit"></button>
    
</form>
